before_install:
  - gem update --system
  - gem --version
language: ruby
cache: bundler
rvm:
- 2.2.0

install: bundle install
# Assume bundler is being used, install step will run `bundle install`.
script: bundle exec jekyll serve

