language: ruby
cache: bundler
rvm:
- 2.2.0

install: bundle install
# Assume bundler is being used, install step will run `bundle install`.
script: proof.sh
branches:
  only:
    - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
