---
baseurl: " "
description: "Programming blog and portfolio site demonstrating my passion, skills, and some projects. Helping reinforce my expanding knowledge and provide a reference for when I need reminding."
extensions:
  - smart
  - autolink
  - tables
  - no_intra_emphasis
  - strikethrough
  - underline
  - quote
  - footnotes
gems:
  - sass
  - bourbon
  - neat
  - bitters
  - refills
github_username: bradbergeron-us
kramdown:
  input: GFM