# Site settings  Reference: http://jekyllrb.com/docs/configuration/
# Build settings
markdown: redcarpet
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - smart

#Meta-Data
title: "Soul Searching Code Scratchpad"
email: "bergeron.bradley@gmail.com"
description: "Programming blog and portfolio site demonstrating my passion, skills, and some projects. Helping reinforce my expanding
knowledge and provide a reference for when I need reminding."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bradbergeron-us.github.io" # the base hostname & protocol for your site
twitter_username: "babergeron"
github_username:  "bradbergeron-us"
highlighter: pygments
kramdown:
  input: GFM

assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/posts
  css_compressor: sass
  js_compressor:  uglifier
  cache:          true

tags:
  template: _layouts/archive

categories:
  template: _layouts/archive

archives:
  template: _layouts/archive

# Exclude:
# - Gemfile
# - Gemfile.lock
# - Rakefile
# - .gitignore

# Gem Dependencies
# gems:
#   -jekyll-autolink_email
#   -jekyll-compass
#   -mini_magick
#   -github-pages
#   -jekyll-sitemap
#   -jekyll-paginate
#   -jekyll-feed
#   -jekyll-smartify
#   -jekyll-redirect-from
#   -bourbon
#   -neat
#   -bitters
#   -compass
#   -octopress-social

