--- 
ASSET_PATH: /_assets
BASE_PATH: "http://Bradbergeron-us.github.io/"
archive_path: /archive.html
atom_path: /atom.xml
email: bergeron.bradley@gmail.com
exclude: 
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - package.json
github: Bradbergeron-us.github.com
highlighter: pygments
name: "Bradley Bergeron"
production_url: |-
    http://Bradbergeron-us.github.io
    # All links will be namespaced by BASE_PATH if defined. # Links in your website should always be prefixed with {{BASE_PATH}} # however this value will be dynamically changed depending on your deployment situation. # # CNAME (http://yourcustomdomain.com) #   DO NOT SET BASE_PATH #   (urls will be prefixed with "/" and work relatively) # # GitHub Pages (http://username.github.io) #   DO NOT SET BASE_PATH #   (urls will be prefixed with "/" and work relatively) #     This means always setting the protocol (http|https) or prefixing with "/"
rss_path: /rss.xml
tagline: "Young Developer Exploring Build Tools, Test Driven Development, Enterprise Software Architecture."
title: "Sourcecode Scratchpad"
twitter: babergeron
