# Site settings  Reference: http://jekyllrb.com/docs/configuration/
# Build settings
gems: [sass, bourbon, neat, bitters, refills]
markdown: redcarpet
  extensions: extensions: ["smart", "autolink", "tables", "no_intra_emphasis", "strikethrough", "underline", "quote", "footnotes"]

#Meta-Data
title: "Virtuous Source Scratchpad"
description: "Programming blog and portfolio site demonstrating my passion, skills, and some projects. Helping reinforce my expanding
knowledge and provide a reference for when I need reminding."
baseurl: # the subpath of your site, e.g. /blog/
url: "bradbergeron-us.github.io"  # the base hostname & protocol for your site
twitter_username: "babergeron"
github_username:  "bradbergeron-us"
kramdown:
  input: GFM

# tags:
#   template: _layouts/archive
#
# categories:
#   template: _layouts/archive
#
# archives:
#   template: _layouts/archive
